### ISSUE TITLE
Atari 7800 emulators and blending consecutive TV lines

### ISSUE THREAD

**Issue by Augusto7743** [7800-devtools/a7800#10]
Hello.
Thanks for reading my topic.
All good with you Mike ?

In AtariAge forums have the topic
"7800 - New graphics mode 160C"
https://forums.atariage.com/topic/161987-7800-new-graphics-mode-160c/

"There are no emulator screenshots because the emulators don't do it justice (well... er... they can't actually handle it correctly). The current 7800 emulators don't know anything about blending consecutive TV lines so the images look very poor. However these are the bitmap images passed into my conversion tool"

I have tested the ROM a78 file in A7800 and the screen not is exactly as the screenshots in the topic.
The screenshots are good with much colors.

Only sharing that information and doing an question ...
Really the MAME video render used in A7800 not does blending consecutive TV lines ?
If not perhaps is an feature need to be added in video render ?

Have an nice day and thanks for doing your A7800.

**Comment by msaarna** [comment]
Sorry for the delayed response. Apparently I'm not getting notified on issues, for some reason.

The blending effect in question relies on PAL display quirks, and not just simple phosphor persistence. The truth is, I don't have the time to throw at emulation of this type of display, given it's one demo using this quirk, and emulation of CRT effects are always imperfect approximations.

**Comment by Augusto7743** [comment]
Thanks for repying.
Have an nice week.
