### ISSUE TITLE
mid-line updates are used for all games ?

### ISSUE THREAD

**Issue by Augusto7743** [7800-devtools/a7800#11]
Hello.
Current version 5.2 does mid-line updates.
That feature have an cpu high usage requirement.

Only want understand an detail ... mid-line updates is used for all games ? If not emulating mid-line updates can break game code and graphics ?

Have an nice week.

**Comment by msaarna** [comment]
Mid-line updates are on all the time. A real console allows registers to be changed at any time, so the emulator does too.

**Comment by Augusto7743** [comment]
Thanks for replying.
Which are the problems using an emulator without mid-line update code ? graphics errors ?
Only trying understand it because the A7800 version 5.2 use much at point need change power profile to "performance" even thus use extremely an single core mainly when using pokey or XM.
In moment using version 4.0 , but without mid-line update code does graphics errors or others issues the correct is use the version 5.0.
mid-line update code can't use an secondary cpu core ?

**Comment by msaarna** [comment]
Yeah, without mid-line updated you'll get occasional graphical glitches in some games. Nothing game breaking.

**Comment by Augusto7743** [comment]
Not demanding ...
Not is possible an optimization in midline update code or even an option in A7800 GUI to disable or enable it ? Is much cpu intensive at point AMD FX and others Intel cpus not can run it in good speed.

The midline update code not is in main MAME a7800 source code ? If not in your opinion that feature need to be added in MAME source code ?

**Comment by msaarna** [comment]
With midline updates the rendering code was significantly changed, as were other parts of the emulator, since the new render code allowed for greater cycle accuracy. It's just not practical to switch between the two.

The midline update code isn't in MAME. If MAME wants better 7800 accuracy, then the feature should be added there.

**Comment by Augusto7743** [comment]
@Mike
Thanks for replying.
MAME team need to be reported about the midline update code.

Not demanding ... not is possible any optimization in midline code ? use more cpu cores than single thread ? if not is possible is an limitation in mame video render code ?
