### ISSUE TITLE
Emulating other controllers from PC Mouse

### ISSUE THREAD

**Issue by ColonialViperPilot** [7800-devtools/a7800#2]
I tried to emulate the Paddles, Driving Controller, TrackBall, and Mouse on the emulator and doing some tests with 7800 Basic. I got most of the controllers to work and how to set to read from the PC. The Driving Controller seems to have an issue where it moves in one direction only. Is this the 2600 Driving Controller, or some other Driving Controller set up?

**Comment by msaarna** [comment]
It's the 2600 driving control. Make sure you use the "reset" button at the bottom of the Controller Selection screen, after picking your controller. (it's required)
