### ISSUE TITLE
best lightgun accuracy settings 

### ISSUE THREAD

**Issue by thatman84** [7800-devtools/a7800#3]
Hi,
I am currently trying to figure out the best way to configure lightgun games and am finding that my mouse crosshair is offset to the right by a a fair bit.
Small Update: The alignment of crosshair and onscreen shot is much closer together in the top 1/8 of the screen

Are there any best settings for screen sizing and or calibrating to improve the accuracy. Im not very familiar with the A7800

**Comment by msaarna** [comment]
There's a bit of rounding of X position that happens in the 7800 lightgun games, due to the coarse polling loop used to determine position. That said, the new a7800 v5.0 release has also improved the lightgun accuracy.
