### ISSUE TITLE
Strange issue accessing the a7800 github

### ISSUE THREAD

**Issue by Augusto7743** [7800-devtools/a7800#9]
Hello.
When trying access
https://github.com/7800-devtools/a7800/ using copy paste or clicking in an text link
automatically change to
https://github.com/7800-devtools/a7800/archive/v5.0.zip

Only reporting that strange issue.
Have an nice day.

**Comment by msaarna** [comment]
Thanks for the heads-up. I can't reproduce this as such, but it sounds like a github+browser specific issue. Not a lot I can do here.

**Comment by Augusto7743** [comment]
Thanks.
